services:
  - type: web
    name: optitreasury
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.main:app
    envVars:
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: password
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: optitreasury
